# Generated by Django 4.0.6 on 2022-07-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumer_name', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumer_name', models.CharField(max_length=100)),
                ('customer_gst_number', models.CharField(blank=True, max_length=100)),
                ('billnumber', models.CharField(max_length=100)),
                ('totalammount', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('ammountpaid', models.IntegerField(default=0)),
                ('collectedby', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0.1)),
                ('gst', models.FloatField(default=0.1)),
                ('totalammount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=100)),
                ('costumer_name', models.CharField(max_length=100)),
                ('refrence_number', models.CharField(max_length=100)),
                ('ammount', models.CharField(default=0, max_length=100)),
                ('pan', models.CharField(blank=True, max_length=100)),
                ('date_created', models.CharField(default='2022-07-20', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('purchase_ammount', models.FloatField(default=0)),
                ('product_price', models.FloatField(default=0)),
                ('gst', models.FloatField(default=0)),
            ],
        ),
    ]
