# Generated by Django 4.0.6 on 2022-07-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumers',
            new_name='Costumersmodel',
        ),
        migrations.AlterField(
            model_name='payments',
            name='date_created',
            field=models.CharField(default='2022-07-21', max_length=100),
        ),
    ]
