# Generated by Django 4.0.6 on 2022-07-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_costumersmodel_credit_ammount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='costumer_id',
            field=models.IntegerField(default=0),
        ),
    ]
