# Generated by Django 4.0.6 on 2022-07-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_expenses_alter_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
