# Generated by Django 4.0.6 on 2022-07-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_expenses_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='costumer_name',
            field=models.CharField(default='Non Billable Expense', max_length=100),
        ),
    ]
