# Generated by Django 4.0.6 on 2022-07-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_expenses_costumer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
