# Generated by Django 4.0.6 on 2022-08-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_calendar_servicepayments_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='contact_number',
            field=models.CharField(default='00000000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='costumer_name',
            field=models.CharField(default='GTS', max_length=100),
        ),
    ]
