# Generated by Django 4.0.6 on 2022-09-01 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_calendar_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('ammount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='tasktype',
            field=models.CharField(default='task', max_length=100),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.CharField(default='2022-09-01', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.CharField(default=datetime.date(2022, 9, 1), max_length=100),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date_created',
            field=models.CharField(default='2022-09-01', max_length=100),
        ),
    ]
