# Generated by Django 4.0.6 on 2022-09-07 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_serviceworks_calendar_tasktype_alter_expenses_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='taskid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.CharField(default='2022-09-07', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.CharField(default=datetime.date(2022, 9, 7), max_length=100),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date_created',
            field=models.CharField(default='2022-09-07', max_length=100),
        ),
    ]
