# Generated by Django 4.0.6 on 2022-09-19 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_servicepayments_paymentmode_alter_expenses_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation_number', models.CharField(max_length=100)),
                ('date', models.CharField(default=datetime.date(2022, 9, 19), max_length=100)),
                ('ammount', models.IntegerField(default=0)),
                ('costumer_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.CharField(default='2022-09-19', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.CharField(default=datetime.date(2022, 9, 19), max_length=100),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date_created',
            field=models.CharField(default='2022-09-19', max_length=100),
        ),
    ]
