# Generated by Django 4.0.6 on 2022-10-12 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_estimation_alter_expenses_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='date',
            field=models.CharField(default=datetime.date(2022, 10, 12), max_length=100),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.CharField(default='2022-10-12', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.CharField(default=datetime.date(2022, 10, 12), max_length=100),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date_created',
            field=models.CharField(default='2022-10-12', max_length=100),
        ),
    ]
